import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>CampusDay 2025</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed w-screen bg-pink-200 p-4 shadow-md">
          <div className="container mx-auto flex justify-between items-center">
              <h1 className="text-3xl font-bold text-yellow-600">CampusDay 2025</h1>
              <nav>
                  <ul className="flex space-x-4">
                      <li><Link href="/" className="text-yellow-600 hover:text-yellow-800">Home</Link></li>
                      <li><Link href="/rundown" className="text-yellow-600 hover:text-yellow-800">Rundown</Link></li>
                      <li><Link href="/materi" className="text-yellow-600 hover:text-yellow-800">Materi</Link></li>
                      <li><Link href="/alumni" className="text-yellow-600 hover:text-yellow-800">Alumni</Link></li>
                  </ul>
              </nav>
          </div>
        </header>
        {children}
        <footer className="bg-pink-200 p-4 text-center">
          <p className="text-yellow-600">&copy; 2025 CampusDay. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
